# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
with open('minutes_n_ingredients.csv', 'r') as file:
    data = file.read()
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", dtype=np.int32, skiprows=1)
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
a_1 = np.mean(data[:, 1])
a_2 = np.mean(data[:, 2])
min_1 = np.min(data[:, 1])
min_2 = np.min(data[:, 2])
max_1 = np.max(data[:, 1])
max_2 = np.max(data[:, 2])
med_1 = np.median(data[:, 1])
med_2 = np.median(data[:, 2])
print(f'Среднее значение 2-го столбца: {a_1}, среднее значение 3-го столбца: {a_2}')
print(f'Минимум 2-го столбца: {min_1}, максимум 3-го столбца: {min_2}')
print(f'Минимум 2-го столбца: {max_1}, максимум 3-го столбца: {max_2}')
print(f'Медиана 2-го столбца: {med_1}, медиана 3-го столбца: {med_2}')

Среднее значение 2-го столбца: 21601.00169, среднее значение 3-го столбца: 9.05528
Минимум 2-го столбца: 0, максимум 3-го столбца: 1
Минимум 2-го столбца: 2147483647, максимум 3-го столбца: 39
Медиана 2-го столбца: 40.0, медиана 3-го столбца: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
quant = 0.75
quant_value = np.quantile(data[:, 1], quant)
data_new1 = data[data[:,1] <= quant_value]
data_new1

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
count = 0
for i in data[:, 1]:
    if i == 1:
        count += 1
data_new2 = np.place(data[:, 1], data[:, 1] == 0,1)
print(count)
print(np.min(data))

237
1


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
print(len(np.unique(data[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
print(np.unique(data[:, 2]))
print(len(np.unique(data[:, 2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
data_new3 = data.copy()
data_new3 = data[data[:,2] <= 5]
print(data_new3)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [11]:
data_new4 = data[:, 2] / data[:, 1]
print(np.max(data_new4))
print(data_new4)

24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [20]:
data_new5 = data[np.argsort(data[:, 1])][-100:, 2]
print(np.mean(data_new5))       

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [30]:
data_new6 = data[np.random.choice(data.shape[0], 10)]
print(data_new6)

[[ 37365    105      8]
 [272023     10      7]
 [148493     40     16]
 [187061     25     11]
 [ 34606     65     10]
 [235326     11      7]
 [283538     90      4]
 [ 12243     70     19]
 [424869     65     11]
 [244151      2      4]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [37]:
avg_quantity = np.mean(data[:, 2])
#print(avg_quantity)
data_new7 = data[data[:, 2] <= avg_quantity]
#print(data_new7)
print(len(data_new7[:, 0])/len(data[:, 0])*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [5]:
data_new8=(data[:,1] <= 20) & (data[:,2] <= 5)
data_final=np.hstack((data, data_new8[:, np.newaxis]))
data_final

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [10]:
data_new9 = data[data[:,1]<=20]
data_new10 = data_new9[data_new9[:,2]<=5]
res = (len(data_new10)*100/len(data))
print(res)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [12]:
data_short=data[data[:,1]<=10]
data_default=data[data[:,1]>10]
data_default_new=data_default[data_default[:,1]<=20]
data_long=data[data[:,1]>20]
data_fin=np.arange(149592).reshape(3,12466,4)
data_fin[0][:,1:]=data_short[:12466,:]
data_fin[0][:,0]=0
data_fin[1][:,1:]=data_default[:12466,:]
data_fin[1][:,0]=1
data_fin[2][:,1:]=data_long[:12466,:]
data_fin[2][:,0]=2
data_fin

array([[[     0,  94746,     10,      6],
        [     0,  67660,      5,      6],
        [     0, 366174,      7,      9],
        ...,
        [     0, 420725,      5,      3],
        [     0,   4747,      0,      9],
        [     0, 370915,      5,      4]],

       [[     1, 127244,     60,     16],
        [     1,  23891,     25,      7],
        [     1, 157911,     60,     14],
        ...,
        [     1, 332803,     30,     10],
        [     1, 226117,    300,     10],
        [     1, 455044,     65,      9]],

       [[     2, 127244,     60,     16],
        [     2,  23891,     25,      7],
        [     2, 157911,     60,     14],
        ...,
        [     2,  68428,     70,     10],
        [     2, 312995,   1445,      7],
        [     2,  93651,    240,     12]]])